use bevy::picking::backend::ray::RayMap;
use bevy::prelude::*;

use crate::world::chunk::BChunk;
use crate::world::pos::{BlockFace, BlockPos};
use crate::world::remesh::ChunkSubMesh;

/// A marker component for chunks and subchunks that indicate that they can be
/// raycasted by the picking system. All subchunks generated by chunk remeshing
/// will inherit this component.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash, Component, Reflect)]
pub struct PickableChunk;

/// A component that can be attached to a world entity, allowing it to store the
/// currently selected block by the picking system.
///
/// Note: Only chunks that have a [`PickableChunk`] component will be considered
/// by the picking system, regardless of whether their parent world has a
/// [`PickableWorld`] component or not. The picking system will only update the
/// hovered block of worlds that have a [`PickableWorld`] component, but it will
/// still consider all chunks with a [`PickableChunk`] component for raycasting.
#[derive(Debug, Default, Component, Reflect)]
pub struct PickableWorld {
    /// The block the user is currently hovering over in this world, if any.
    pub hovered: Option<HoveredBlock>,
}

/// A marker component for cameras that should be used by the Boned Cubed
/// picking system to perform raycasts.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq, Hash, Component, Reflect)]
pub struct B3Camera;

/// A struct that represents a block that has been hovered over by the picking
/// system, containing the position of the block and the face that was hit by
/// the raycast.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Reflect)]

pub struct HoveredBlock {
    /// The position of the block that was hovered over.
    pub pos: BlockPos,

    /// The face of the block that was hit by the raycast.
    pub face: BlockFace,
}

pub(super) fn update_hover(
    raymap: Res<RayMap>,
    mut raycast: MeshRayCast,
    mut worlds: Query<(&mut PickableWorld, &GlobalTransform)>,
    chunks: Query<&ChildOf, With<BChunk>>,
    subchunks: Query<&ChildOf, (With<PickableChunk>, With<ChunkSubMesh>)>,
    camera: Query<(), (With<Camera>, With<B3Camera>)>,
) {
    for (mut world, _) in worlds.iter_mut() {
        world.hovered = None;
    }

    let Some(ray) = raymap
        .iter()
        .find(|(id, _)| camera.get(id.camera).is_ok())
        .map(|(_, ray)| *ray)
    else {
        return;
    };

    let filter = |entity| subchunks.get(entity).is_ok();
    let early_exit = |submesh_entity| {
        if let Ok(ChildOf(chunk_entity)) = subchunks.get(submesh_entity) {
            if let Ok(ChildOf(world_entity)) = chunks.get(*chunk_entity) {
                if worlds.get(*world_entity).is_ok() {
                    return true;
                }
            }
        };
        false
    };

    let settings = MeshRayCastSettings::default()
        .with_filter(&filter)
        .with_early_exit_test(&early_exit)
        .with_visibility(RayCastVisibility::VisibleInView);

    let hits = raycast.cast_ray(ray, &settings);

    for (entity, hit) in hits {
        if let Ok(ChildOf(chunk_entity)) = subchunks.get(*entity) {
            if let Ok(ChildOf(world_entity)) = chunks.get(*chunk_entity) {
                if let Ok((mut world, world_transform)) = worlds.get_mut(*world_entity) {
                    let mut hit_world = hit.point - hit.normal * 0.0001; // shift to avoid floating point issues
                    hit_world = world_transform
                        .to_matrix()
                        .inverse()
                        .transform_point3(hit_world)
                        .floor();

                    let pos: BlockPos = hit_world.as_ivec3().into();
                    let face = BlockFace::from_normal(hit.normal);
                    world.hovered = Some(HoveredBlock { pos, face });
                    break;
                }
            }
        }
    }
}
