use bevy::prelude::*;

use crate::world::chunk::BChunk;
use crate::world::picking::PickableWorld;
use crate::world::pos::BlockFace;
use crate::world::world::BWorld;

/// The plugin responsible for rendering gizmos related to Bones Cubed, such as
/// chunk borders and orphaned chunk indicators. This plugin is only included
/// when the `gizmos` feature is enabled, allowing users to opt-in to these
/// visual debugging tools as needed.
///
/// Gizmos can cause some performance overhead and are visually cluttering, so
/// they are disabled by default in the settings. Users can enable specific
/// gizmos through the [`B3GizmosSettings`] resource, or enable all gizmos by
/// default using the `gizmos-all` feature flag.
pub struct B3GizmosPlugin;
impl Plugin for B3GizmosPlugin {
    fn build(&self, app_: &mut App) {
        app_.init_resource::<B3GizmosSettings>()
            .init_gizmo_group::<BonesCubedGizmoGroup>()
            .add_systems(
                PostUpdate,
                (
                    draw_chunk_borders.in_set(GizmosSystemSet::DrawChunkBorders),
                    hovered_block.in_set(GizmosSystemSet::DrawHoveredBlock),
                ),
            )
            .configure_sets(
                PostUpdate,
                (
                    GizmosSystemSet::DrawChunkBorders.after(TransformSystems::Propagate),
                    GizmosSystemSet::DrawHoveredBlock.after(TransformSystems::Propagate),
                ),
            );
    }
}

#[derive(SystemSet, Debug, Hash, PartialEq, Eq, Clone)]
pub enum GizmosSystemSet {
    DrawChunkBorders,
    DrawHoveredBlock,
}

/// Settings for the Bones Cubed gizmos plugin, allowing users to enable or
/// disable specific gizmos as needed.
#[derive(Resource)]
pub struct B3GizmosSettings {
    /// Renders yellow wireframe cubes around each chunk to visualize their
    /// borders.
    pub chunk_borders: bool,

    /// Renders red wireframe cubes around chunks that are not attached to a
    /// world. When used in conjunction with `chunk_borders`, orphaned chunks
    /// will replace the yellow wireframe with a red one, making them easier to
    /// identify.
    pub orphaned_chunks: bool,

    /// Renders an aqua wireframe square around the face of the block currently
    /// being hovered over by the cursor.
    pub hovered_block: bool,
}

// Enable all gizmos by default
#[cfg(feature = "gizmos-all")]
impl Default for B3GizmosSettings {
    fn default() -> Self {
        Self {
            chunk_borders: true,
            orphaned_chunks: true,
            hovered_block: true,
        }
    }
}

// Disable all gizmos by default
#[cfg(not(feature = "gizmos-all"))]
impl Default for B3GizmosSettings {
    fn default() -> Self {
        Self {
            chunk_borders: false,
            orphaned_chunks: false,
            hovered_block: false,
        }
    }
}

/// The gizmo group for Bones Cubed, containing all gizmos generated by the
/// plugin.
#[derive(Default, Reflect, GizmoConfigGroup)]
pub struct BonesCubedGizmoGroup;

/// Draws yellow wireframe cubes around each chunk to visualize their borders.
/// If the `orphaned_chunks` setting is enabled, chunks that are not attached to
/// a world will be drawn with red wireframe cubes instead, making them easier
/// to identify.
fn draw_chunk_borders(
    settings: Res<B3GizmosSettings>,
    worlds: Query<(), With<BWorld>>,
    chunks: Query<(&GlobalTransform, Option<&ChildOf>), With<BChunk>>,
    mut gizmos: Gizmos<BonesCubedGizmoGroup>,
) {
    if !settings.chunk_borders && !settings.orphaned_chunks {
        return;
    }

    for (transform, maybe_parent) in &chunks {
        let is_orphaned = maybe_parent
            .map(|parent| !worlds.contains(parent.parent()))
            .unwrap_or(true);

        let mat = transform
            .mul_transform(Transform::from_translation(Vec3::ONE * 8.0))
            .mul_transform(Transform::from_scale(Vec3::ONE * 16.0))
            .to_matrix();

        if is_orphaned && settings.orphaned_chunks {
            gizmos.cube(mat, Color::srgb(1.0, 0.0, 0.0));
        } else if settings.chunk_borders {
            gizmos.cube(mat, Color::srgb(1.0, 1.0, 0.0));
        }
    }
}

/// Draws an aqua wireframe square around the face of the block currently being
/// hovered over by the cursor, allowing users to easily identify which block
/// they are targeting for interactions such as placing or breaking.
fn hovered_block(
    settings: Res<B3GizmosSettings>,
    worlds: Query<(&PickableWorld, &GlobalTransform)>,
    mut gizmos: Gizmos<BonesCubedGizmoGroup>,
) {
    if !settings.hovered_block {
        return;
    }

    for (pickable, transform) in &worlds {
        let Some(hovered) = pickable.hovered else {
            continue;
        };

        let pos = hovered.pos.as_vec3() + Vec3::ONE * 0.5 + hovered.face.normal() * 0.5;
        let target = pos + hovered.face.normal();
        let up = match hovered.face {
            BlockFace::Top | BlockFace::Bottom => Vec3::X,
            _ => Vec3::Y,
        };

        let mat = transform
            .mul_transform(
                Transform::from_scale(Vec3::new(1.0, 1.0, 0.0))
                    .with_translation(pos)
                    .looking_at(target, up),
            )
            .to_matrix();
        gizmos.cube(mat, Color::srgb(0.0, 1.0, 1.0));
    }
}
